package satunnaisoliot.datastructures.enums;

public enum FieldType {

    ADDRESS, ANNOTE, AUTHOR, BOOKTITLE, CHAPTER, CROSSREF, EDITION, EDITOR, HOWPUBLISHED, INSTITUTION, JOURNAL, BIBKEY, MONTH, NOTE, NUMBER, ORGANIZATION, PAGES, PUBLISHER, SCHOOL, SERIES, TITLE, TYPE, VOLUME, YEAR,
}
