CREATE TABLE Reference (
  id SERIAL PRIMARY KEY,
  reference_type varchar,
  bibtex_key varchar,
  address varchar,
  annote varchar,
  author varchar,
  booktitle varchar,
  chapter varchar,
  crossref varchar,
  edition varchar,
  howpublished varchar,
  institution varchar,
  journal varchar,
  bibkey varchar,
  month varchar,
  note varchar,
  number varchar,
  organization varchar,
  pages varchar,
  publisher varchar,
  school varchar,
  series varchar,
  title varchar,
  type varchar,
  volume varchar,
  year varchar
);