CREATE TABLE IF NOT EXISTS Reference (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  reference_type varchar,
  bibtex_key varchar,
  address varchar,
  annote varchar,
  author varchar,
  booktitle varchar,
  chapter varchar,
  crossref varchar,
  edition varchar,
  editor varchar,
  howpublished varchar,
  institution varchar,
  journal varchar,
  bibkey varchar,
  month varchar,
  note varchar,
  number varchar,
  organization varchar,
  pages varchar,
  publisher varchar,
  school varchar,
  series varchar,
  title varchar,
  type varchar,
  volume varchar,
  year varchar
);